DROP TABLE IF EXISTS Utenti;
DROP TABLE IF EXISTS HP_POSLLH;
DROP TABLE IF EXISTS HP_POSECEF;
DROP TABLE IF EXISTS STATUS;

CREATE TABLE IF NOT EXISTS 'Utenti' (
	Nome VARCHAR(50),
	Cognome VARCHAR(50),
	Email VARCHAR(50) PRIMARY KEY,
	Password VARCHAR(50),
	UNIQUE(Email)
);

CREATE TABLE IF NOT EXISTS 'HPPOSLLH' (
	version TEXT,
	reserved0 TEXT,
	invalidLlh BOOLEAN,
	iTOW INT PRIMARY KEY,
	lon REAL(10, 7),
	lat REAL(10, 7),
	height INT,
	hMSL INT,
	lonHp REAL(10, 9),
	latHp REAL(10, 9),
	heightHp INT,
	hMSLHp INT,
	hAcc INT,
	vAcc INT
);

CREATE TABLE IF NOT EXISTS 'HPPOSECEF' (
	version TEXT,
	reserved0 TEXT,
	iTOW INT PRIMARY KEY,
	ecefX DOUBLE,
	ecefY DOUBLE,
	ecefZ DOUBLE,
	ecefXHp DOUBLE,
	ecefYHp DOUBLE,
	ecefZHp DOUBLE,
	invalidEcef BOOLEAN,
	pAcc INT
);

CREATE TABLE IF NOT EXISTS 'STATUS' (
	iTOW INT PRIMARY KEY,
	gpsFix TEXT,
	gpsFixOk BOOLEAN,
	diffSoln BOOLEAN,
	wknSet BOOLEAN,
	towSet BOOLEAN,
	diffCorr BOOLEAN,
	carrSolnValid BOOLEAN,
	mapMatching INT,
	psmState INT,
	spoofDetState INT,
	carrSoln INT,
	ttff INT,
	msss INT
);